//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Common.Security.Library.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public int C_id { get; set; }
        public string userId { get; set; }
        public string RefreshToken { get; set; }
        public string Sessiontoken { get; set; }
        public string UserAgent { get; set; }
        public string DeviceId { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string Details { get; set; }
    }
}
